intershop/helm-charts

- .github/callBump2version.py
- charts/icm-as/README.md
- charts/icm-web/README.md
- charts/icm/.bumpversion.cfg
- charts/icm/.helmignore
- charts/icm/Chart.yaml
- charts/icm/README.md
- charts/icm/requirements.yaml
- charts/icm/values.yaml
[x] Feature
No icm-chart release available in helm repository.
icm-chart is available in https://intershop.github.io/helm-charts
[x] No
> Release ICM Helm Chart 0.2.8

- charts/icm/Chart.yaml
- charts/icm/requirements.yaml
[x] Bugfix
Could not release charts
Issue Number: Closes #12
[x] No
> Release chart release fix

- .github/callBump2version.py
- charts/icm-replication/.bumpversion.cfg
- charts/icm-replication/.helmignore
- charts/icm-replication/Chart.yaml
- charts/icm-replication/README.md
- charts/icm-replication/requirements.yaml
- charts/icm-replication/values.yaml
- charts/icm/Chart.yaml
- charts/icm/requirements.yaml
- charts/icm/values.yaml
* #14: use relative folders for local dependencies
* #14: use relative folders for local dependencies
* #12: delivers icm-replication
* #12: also add icm-replication to bum version support
* #12: use tabs instead of spaces
* fix: use placeholders for folder definitions (#12)
* fix: working sample by putting dependencies back into the Chart.yaml
(#12)
* #14: use relative folders for local dependencies
* #12: delivers icm-replication
* #12: also add icm-replication to bum version support
* #12: use tabs instead of spaces
* fix: use placeholders for folder definitions (#12)
* fix: working sample by putting dependencies back into the Chart.yaml
(#12)
* rebase with develop/icm (#12)
* fix: chart version updated (#12)
* feat: a license block to default values.yaml of icm and icm-replication
[x] …
> Feature/new icm replication chart (#18)

- charts/icm-as/.bumpversion.cfg
- charts/icm-as/Chart.yaml
- charts/icm-as/templates/as-deployment.yaml
[x] Bugfix
Wrong debug and jmx ports are mapped.
Issue Number: Closes #29
Ports are mapped correctly.
[x] No
> fix: portmapping was wrong (#29)

- .github/callBump2version.py
- charts/icm-as/.bumpversion.cfg
- charts/icm-as/Chart.yaml
- charts/icm-as/templates/as-deployment.yaml
- charts/icm-replication/.bumpversion.cfg
- charts/icm-replication/.helmignore
- charts/icm-replication/Chart.yaml
- charts/icm-replication/README.md
- charts/icm-replication/requirements.yaml
- charts/icm-replication/values.yaml
- charts/icm/Chart.yaml
- charts/icm/requirements.yaml
- charts/icm/values.yaml
[x] Bugfix
Wrong ports where mapped
Issue Number: Closes #29
ports mapped correctly
[x] No
> Fix port mapping

- charts/icm-replication/.bumpversion.cfg
- charts/icm-replication/Chart.yaml
- charts/icm-replication/requirements.yaml
- charts/icm/.bumpversion.cfg
- charts/icm/Chart.yaml
- charts/icm/requirements.yaml
[x] Bugfix
Issue Number: Closes #29
[ ] Yes
[x] No
> fix: roll out port mapping fix (#29)

- charts/icm-replication/.bumpversion.cfg
- charts/icm-replication/Chart.yaml
- charts/icm-replication/requirements.yaml
- charts/icm/.bumpversion.cfg
- charts/icm/Chart.yaml
- charts/icm/requirements.yaml
[x] Bugfix
Issue Number: Closes #29
[x] No
> Release port mapping changes to main

- charts/icm-as/templates/as-deployment.yaml
[x] Bugfix
Icm-as pod doesn't start becaus startup probe on "/" fails
Tho pod starts as expected
[x] No
> fix: startup probe fixed

- charts/icm-as/.bumpversion.cfg
- charts/icm-as/Chart.yaml
- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/values.yaml
- charts/icm-replication/.bumpversion.cfg
- charts/icm-replication/Chart.yaml
- charts/icm-replication/requirements.yaml
- charts/icm/.bumpversion.cfg
- charts/icm/Chart.yaml
- charts/icm/requirements.yaml
[x] Bugfix
Wrong startup probe icm-as.
Startup probe of icm-as works.
[x] No
> ICM: Fix startup probe

- charts/icm-replication/values.yaml
- charts/icm/values.yaml
[x] Bugfix
We have double version tags during test run
test runs
[ ] Yes
[x] No
> fix: version tags shall be configured in repository field

- charts/icm-replication/.bumpversion.cfg
- charts/icm-replication/Chart.yaml
- charts/icm-replication/requirements.yaml
[x] Bugfix
[ ] Feature
Sub subchart of icm-replication isn't there within tgz.
Issue Number: Closes #49
Sub subchart is resolved within tgz
[ ] Yes
[n] No
> fix: without using relative dependencies (#49)

- charts/iom/.helmignore
[x] Bugfix
[ ] Feature
Issue Number: Closes ADO issue 76859
docs removed from helm package
[ ] Yes
[x] No
> fix(iom): add docs to .helmignore (#76859)

- .github/workflows/lint-test.yml
do not test if no chart changes are detected
> fix: if no chart change then no cluster and now no chart-testing

- charts/icm-replication/requirements.yaml
> fix: replication release

- charts/iom/README.rst
- charts/iom/docs/ParametersIOM.rst
- charts/iom/templates/statefulset.yaml
- charts/iom/values.yaml
[ ] Bugfix
[ x ] Feature
Helm parameter *mailResourcesBaseUrl* was removed.
[ ] Yes
[ x ] No
> feature(iom): remove mail resources base url (#77222)

- charts/icm-web/templates/wa-deployment.yaml
- charts/icm-web/templates/waa-deployment.yaml
- charts/icm-web/values.yaml
[x] Feature
Webadapter agent and webadapter pod and deployment could be enhanced with labels and annotations.
Issue Number: Closes #77
> feat: add configurations to helm chart (#77)

- charts/icm-replication/.bumpversion.cfg
- charts/icm-replication/Chart.yaml
- charts/icm-replication/requirements.yaml
- charts/icm-web/.bumpversion.cfg
- charts/icm-web/Chart.yaml
- charts/icm/.bumpversion.cfg
- charts/icm/Chart.yaml
- charts/icm/requirements.yaml
Merge release changes back to develop/icm
> ICM: Release/icm/v0.2.15

- charts/icm-replication/.bumpversion.cfg
- charts/icm-replication/Chart.yaml
- charts/icm-replication/requirements.yaml
- charts/icm-web/.bumpversion.cfg
- charts/icm-web/Chart.yaml
- charts/icm-web/templates/wa-deployment.yaml
- charts/icm-web/templates/waa-deployment.yaml
- charts/icm/.bumpversion.cfg
- charts/icm/Chart.yaml
- charts/icm/requirements.yaml
[x ] Bugfix
PageCache PVC is not used in the web adapter deployment 
PageCache PVC is used in the web adapter deployment 
[ ] Yes
[x ] No
> fix: use PageCache PVC (#87)

- charts/iom/Chart.yaml
- charts/iom/README.rst
- charts/iom/docs/ExampleDemo.rst
- charts/iom/docs/ExampleProd.rst
- charts/iom/docs/ParametersIOM.rst
- charts/iom/docs/ToolsAndConcepts.rst
- charts/iom/values.yaml
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
[ x ] Application / infrastructure changes
New Intershop Docker repository at docker.tools.intershop.com is now used.
[ x ] Yes
[ ] No
> feat(iom)!: use new ISH Docker repo (#78056)

- charts/icm-as/.bumpversion.cfg
- charts/icm-as/Chart.yaml
- charts/icm-as/templates/config-replication-clusters-xml-cm.yaml
- charts/icm-replication/.bumpversion.cfg
- charts/icm-replication/Chart.yaml
- charts/icm-replication/requirements.yaml
- charts/icm/.bumpversion.cfg
- charts/icm/Chart.yaml
- charts/icm/requirements.yaml
[x ] Bugfix
[ ] Feature
Edit System does not start because of SAXParseException
Issue Number: Closes #106 
Edit System does start
[ ] Yes
[x ] No
> fix: relication configmap (#106)

- .github/workflows/lint-test_icm.yml
- charts/icm-as/README.md
- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/templates/local-sites-pv.yaml
- charts/icm-as/templates/local-sites-pvc.yaml
- charts/icm-as/templates/tests/test-connection.yaml
- charts/icm-as/values.yaml
- charts/icm-web/templates/local-pagecache-pv.yaml
- charts/icm-web/templates/local-pagecache-pvc.yaml
- charts/icm-web/templates/wa-deployment.yaml
- charts/icm/values.yaml
- ct_icm.yaml
[x] Feature
Only `ct lint` is executed during PR-test.
Issue Number: Closes #103
`ct install` installs all icm charts
[x] No
> ICM: do ct install

- charts/icm-as/templates/config-replication-clusters-xml-cm.yaml
[x] Bugfix
Count parse replication-cluster.xml
Issue Number: Closes #112
> fix: remove comment sign (#112)

- .github/workflows/lint-test_icm-as.yml
- charts/icm-as/templates/tests/test-connection.yaml
- charts/icm-as/values.yaml
- charts/icm/values.yaml
- ct_icm-as.yaml
[ ] Bugfix
[x] Feature
Only icm-chart is tested
Issue Number: Closes #119
Split test between icm-as and icm
[ ] Yes
[x] No
> feat: added new test for icm-as and changed testing url (#119)

- .github/workflows/lint-test_icm-as.yml
- charts/icm-as/templates/tests/test-connection.yaml
- charts/icm-as/values.yaml
- charts/icm/values.yaml
- ct_icm-as.yaml
[ ] Bugfix
[x] Feature
Icm-as test added
Issue Number: Closes #119
[ ] Yes
[n] No
> Fb 119 add test for icmas

- charts/icm-replication/.bumpversion.cfg
- charts/icm-replication/Chart.yaml
- charts/icm-replication/requirements.yaml
- charts/icm-web/.bumpversion.cfg
- charts/icm-web/Chart.yaml
- charts/icm-web/README.md
- charts/icm-web/templates/wa-deployment.yaml
- charts/icm-web/templates/waa-deployment.yaml
- charts/icm-web/values.yaml
- charts/icm/.bumpversion.cfg
- charts/icm/Chart.yaml
- charts/icm/requirements.yaml
[ ] Bugfix
[x] Feature
We have an own way of setting resources on web pod.
Issue Number: Closes #123
There is a standard way of doing so.
[ ] Yes
[x] No
> ICM: Resouces on web pods shall be set the standard way

- charts/icm-as/.bumpversion.cfg
- charts/icm-as/Chart.yaml
- charts/icm-as/system-conf/cluster/empty-config.xml
- charts/icm-replication/.bumpversion.cfg
- charts/icm-replication/Chart.yaml
- charts/icm-replication/requirements.yaml
- charts/icm/.bumpversion.cfg
- charts/icm/Chart.yaml
- charts/icm/requirements.yaml
[x ] Bugfix
Error during helm install config-map already exists
Issue Number: Closes #129 
helm install without Error 
[ ] Yes
[ x] No
> fix (icm): config map already exists (#129)

- .github/workflows/lint-test_icm-as.yml
- .gitignore
- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/templates/cluster-sc.yaml
- charts/icm-as/templates/cluster-sites-pvc.yaml
- charts/icm-as/tests/README.md
- charts/icm-as/tests/basic-config-values_test.yaml
- charts/icm-as/tests/custom-command_test.yaml
- charts/icm-as/tests/customizations_test.yaml
- charts/icm-as/tests/default-values_test.yaml
- charts/icm-as/tests/environment_test.yaml
- charts/icm-as/tests/fullname-override_test.yaml
- charts/icm-as/tests/image_test.yaml
- charts/icm-as/tests/license_test.yaml
- charts/icm-as/tests/name-override_test.yaml
- charts/icm-as/tests/persistence-customdata_test.yaml
- charts/icm-as/tests/persistence-jgroups_test.yaml
- charts/icm-as/tests/persistence-sites_test.yaml
- charts/icm-as/tests/pod-security-context_test.yaml
- charts/icm-as/tests/probes-liveness_test.yaml
- charts/icm-as/tests/probes-readiness_test.yaml
- charts/icm-as/tests/probes-startup_test.yaml
- charts/icm-as/tests/provide-custom-config_test.yaml
- charts/icm-as/tests/resources_test.yaml
- charts/icm-as/tests/serviceaccount-create_test.yaml
- charts/icm-as/tests/values/customCommand.yaml
- charts/icm-as/tests/values/imagePullSecrets.yaml
- charts/icm-as/values.yaml
[x] Build-related changes
Helm chart is checked with lint and integration tested trying an install but not unit tested.
Helm chart is checked with lint and integration tested trying an install and unit tested.
[ ] Yes
[x] No
> ICM: Feature/add helm chart unit tests (#139)

- .github/workflows/lint-test_icm-as.yml
[x] Bugfix
`ct lint` fails
Issue Number: Closes #147
> chore (icm): fix related file name for ct lint (#147)

- charts/pwa/README.md
- charts/pwa/values.yaml
[ ] Bugfix
[ ] Feature
[ X ] Documentation content changes
Patch
The provided example command line in `README.md` doesn't produce a running example installation
The provided example command line in `README.md` produces a running example installation
[ ] Yes
[ X ] No
> chore: provide example pwa deployment

- .github/workflows/bump-version.yml
- .github/workflows/lint-test_icm-as.yml
- .github/workflows/lint-test_icm.yml
- .github/workflows/lint-test_pwa.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/release-charts.yml
[ ] Bugfix
[ ] Feature
[ X ] CI-related changes
Deprecation warnings in pipeline run: `Node.js 12 actions are deprecated.` [GitHub Blog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
Upgraded most actions.
[ ] Yes
[ X ] No
> chore: upgrade github actions

- charts/iom/values.yaml
[ ] Bugfix
[ ] Feature
[ x ] Application / infrastructure changes
default value of dbaccount.image.tag was changed to 1.6.0
[ ] Yes
[ x ] No
> chore(iom): updated default value of dbaccount tag (#80537)

- charts/iom/README.rst
[ ] Bugfix
[ ] Feature
[ ] Yes
[ ] No
> docs: document review

- .github/workflows/lint-test_pwa.yml
- .github/workflows/release-charts.yml
- charts/pwa/Chart.lock
- charts/pwa/Chart.yaml
- charts/pwa/README.md
- charts/pwa/templates/_helpers.tpl
- charts/pwa/templates/deployment.yaml
- charts/pwa/values.schema.json
- charts/pwa/values.yaml
[ ] Bugfix
[ X ] Feature
[ X ] CI-related changes
Intershop PWA supports hybrid mode where one can gradually switch from classic storefront pages to Angular based pages. This is also called hybrid approach. A helm chart supporting that kind of deployment was yet missing.
Deploy Intershop PWA in hybrid mode is now supported.
[ X ] Yes
[ ] No
With this release we added a conditional dependency to ICM
```
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                                       
intershop/icm            	0.5.0        	11.0.0     	Intershop Commerce Management …
```
> release: pwa-main version 0.4.0 

- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/templates/mssql-deployment.yaml
- charts/icm-as/templates/mssql-service.yaml
- charts/icm-as/values.yaml
- charts/icm/values.yaml
[ ] Bugfix
[x] Feature
[x] Application / infrastructure changes
Database credentials must be declared explicitly, not via generic environment variables
[ x] Yes
[ ] No
> feat: add mssql for developers (#184)

- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/tests/license_test.yaml
- charts/icm-as/values.yaml
[x] Feature
Issue Number: Closes #144
License could be set as k8s secret.
[ ] Yes
[x] No
> feat (icm): enable icm license secret configuration (#144)

- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/tests/environment_test.yaml
[ ] Bugfix
[x] Feature
Issue Number: Closes #190 
Deployment provides K8s information to ICM application like: NodeName, Namespace and PodName.
[ ] Yes
[x] No
> Feature/icm/feat add k8s server info (#190)

- charts/icm/values-iste_linux.tmpl
[x] Bugfix
htmlunit tests do fail with some mail connection exception
Issue Number: Closes #209
htmlunit tests don not fail anymore
[x] No
> fix (icm): fix INTERSHOP_SMTPSERVER value (#209)

- charts/icm/values-iste_linux.tmpl
[x] Bugfix
Testmails could not be send
Issue Number: Closes #209
mails could be send
[ ] Yes
[x] No
> fix (icm): mail shall now be correct on both ends (#209)

- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/tests/default-values_test.yaml
- charts/icm-as/tests/probes-liveness_test.yaml
- charts/icm-as/tests/probes-readiness_test.yaml
- charts/icm-as/tests/probes-startup_test.yaml
[x] Bugfix
[ ] Feature
The appserver management connector is used for the probes and the shutdown.
[ ] Yes
[x] No
> use appserver management connector

- charts/icm/templates/test-job.yaml
- charts/icm/values-iste_linux.tmpl
[x] Bugfix
Test fail because of invalid shell code
Issue Number: Closes #223
Test will succeed 
[ ] Yes
[x] No
> fix (icm): update testrun call (#223)

- charts/icm-web/values.yaml
- charts/icm/Chart.yaml
[x] Bugfix
wa gets stopped with 137
Issue Number: Closes #229
wa runs
[ ] Yes
[x] No
> fix (icm): increase memory again (#229)

- charts/icm/values-iste_linux.tmpl
- charts/icm/values.yaml
[x] Bugfix
webadapter misses evict annotation
Issue Number: Closes #232
webadapter hast evict annotation
[ ] Yes
[x] No
> fix (icm): webadapter now also get evict annotation (#232)

- charts/icm/templates/test-job.yaml
- charts/icm/values-iste_linux.tmpl
[x] Feature
pagedump folder are generated and hold as they are
Issue Number: Closes #237
pagedump folder is zipped and removed
[ ] Yes
[x] No
> fix (icm): zip pagedump folder and remove it (#237)

- charts/icm/Chart.yaml
- charts/icm/values-iste_linux.tmpl
[x] Feature
testrunner take too much cpu
Issue Number: Closes #245
testrunner cpu limit reduced
[ ] Yes
[x] No
> feat (icm): adjust cpu limits (#245)

- README.md
- charts/pwa/README.md
- charts/pwa/ci/cache-channels.yaml
- charts/pwa/docs/migrate-to-0.3.0.md
- charts/pwa/docs/migrate-to-0.7.0.md
- charts/pwa/templates/_helpers.tpl
- charts/pwa/values.schema.json
- charts/pwa/values.yaml
[x] Documentation content changes
Inconsistent terminology for PWA Hybrid Approach. 
The Hybrid Approach was sometimes referred to as hybrid mode. This PR standardizes the wording. 
Additionally example configurations and migration notes have been extended.
**Note:** These changes will not result in a new release since only documentation and examples where changed. No changes in functionality.
No.
> Replace Hybrid Mode by Hybrid Approach.

- charts/icm-replication/values.yaml
- charts/icm-web/values.yaml
- charts/icm/start-test-local_vars.sh
- charts/icm/values.yaml
[x] Bugfix
[ ] Feature
Closes #261
[ ] Yes
[x] No
> fix (icm): Update icm-webadapter to version 2.4.6 (#261)

- charts/icm-as/templates/mssql-deployment.yaml
- charts/icm-as/tests/mssql-support_test.yaml
- charts/icm-as/values.yaml
[x] Bugfix
[x] Feature
Currently the developer MS SQL database will be recreated during startup.
Issue Number: Closes #201 
This feature allows to enable or disable the creation.
[ ] Yes
[x] No
> feat: enable/disable recreation of database (#201)

- .github/template/base/action.yml
- .github/template/unittest/action.yml
- charts/icm-as/templates/mssql-deployment.yaml
- charts/icm-as/tests/default-values_test.yaml
- charts/icm-as/tests/license_test.yaml
- charts/icm-as/tests/persistence-sites_test.yaml
- charts/icm-as/values.yaml
[ ] Bugfix
[x ] Feature
MSSQL Container has hardcoded resource limits 
[ ] Yes
[x] No
> ICM: Create configuration option for CPU and Memory of MSSQL 

- charts/icm-as/templates/_environments.tpl
- charts/icm-as/templates/_helpers.tpl
- charts/icm-as/templates/_volumeMounts.tpl
- charts/icm-as/templates/_volumes.tpl
- charts/icm-as/templates/as-deployment.yaml
See Issue Number: Closes #295 
[ ] Yes
[ x ] No
> fix(icm): reenable weblayer (#295)

- .github/pull_request_template.md
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
Issue Number: Closes #298 
[ ] Yes
[ x ] No
> docs: fix invalid markdown in pr template (#298)

- charts/icm-as/README.md
- charts/icm-as/templates/_volumes.tpl
- charts/icm-as/tests/persistence-jgroups_test.yaml
- charts/icm-as/tests/persistence-sites_test.yaml
- charts/icm-as/values.yaml
- charts/icm-web/templates/wa-deployment.yaml
- charts/icm-web/templates/waa-deployment.yaml
- charts/icm-web/values.yaml
Issue Number: Closes #310 
Azure files will be mounted with user and group of pod security context.
Existing files will be fixed.
> fix: file ownership for azure file shares

- charts/icm-as/README.md
- charts/icm/README.md
Less documentaion
Issue Number: Closes #330
More documentation
> feat (icm): describe chart testing (#330)

- charts/icm-as/README.md
- charts/icm-as/templates/_environments.tpl
- charts/icm-as/templates/_volumeMounts.tpl
- charts/icm-as/templates/_volumes.tpl
- charts/icm-as/templates/config-newrelic-yaml-cm.yaml
- charts/icm-as/tests/newrelic_test.yaml
- charts/icm-as/values.yaml
With ICM-AS 11.3.0 container provides New Relic integration of java agent. This new feature enable the activation of that feature via helm charts. Older versions of ICM-AS can use the new helm chart with deactivated feature.
Issue Number: Closes #333
> feat: add NewRelic Integration (#333)

- charts/icm-replication/requirements.yaml
> fix (icm): release number was wrong (#356)

- charts/icm-as/values.yaml
values.yaml is wrong with storageClass-Configuration for jGroups
Issue Number: Closes #361
Default configuration fixed
> fix (icm): storageClass configuration had changed (#361)

- charts/icm-replication/values-iste_linux.tmpl
- charts/icm/values-iste_linux.tmpl
Newrelic data isn't monitored for test environment
Issue Number: Closes #364
Newrelic data is monitored for test environment
> feat (icm): add new relic configuration to iste tmpl (#364)

- charts/icm-web/values.yaml
- charts/icm/Chart.yaml
* internal index of pagecache needs some additional ram
Issue Number: Closes #367
> fix: WAA limits (#367)

- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/values.yaml
- charts/icm-web/templates/wa-deployment.yaml
- charts/icm-web/templates/waa-deployment.yaml
- charts/icm-web/values.yaml
Update strategy is not configurable
Issue Number: Closes #372
Update strategy is configurable
> feat (icm): configurable update strategy (#372)

- charts/icm-as/templates/_environments.tpl
- charts/icm-as/templates/_helpers.tpl
- charts/icm-as/templates/_operationalContext.tpl
- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/templates/config-newrelic-yaml-cm.yaml
- charts/icm-as/tests/default-values_test.yaml
- charts/icm-as/tests/environment_test.yaml
- charts/icm-as/tests/newrelic_test.yaml
- charts/icm-as/values.yaml
- charts/icm-web/templates/_operationalContextWeb.tpl
- charts/icm-web/templates/wa-deployment.yaml
- charts/icm-web/templates/waa-deployment.yaml
- charts/icm-web/values.yaml
There's no operational context centrally configurable.
Issue Number: Closes #379 
There's a operational context centrally configurable.
> feat (icm): provide operational context (#379)

- charts/icm-web/templates/cluster-logs-pvc.yaml
- charts/icm-web/templates/cluster-logs-sc.yaml
- charts/icm-web/templates/local-logs-pv.yaml
- charts/icm-web/templates/local-logs-pvc .yaml
- charts/icm-web/templates/nfs-logs-pv.yaml
- charts/icm-web/templates/nfs-logs-pvc.yaml
- charts/icm-web/templates/wa-deployment.yaml
- charts/icm-web/values.yaml
Issue Number: Closes #382 
The WA values file can declare mount points for WA-Request logs.
> feat: writes WA-logs to external storage (#382)

- charts/icm-as/templates/_environments.tpl
- charts/icm-as/templates/_helpers.tpl
- charts/icm-as/tests/newrelic_test.yaml
- charts/icm-as/values.yaml
Issue Number: Closes #377 
NewRelic nri-prometheus can recognize icm-as.
> feat: provide annotations about prometheus endpoints (#377)

- charts/icm-as/templates/_environments.tpl
- charts/icm-as/templates/_volumeMounts.tpl
- charts/icm-as/templates/_volumes.tpl
- charts/icm-as/templates/ingress.yaml
- charts/icm-as/templates/redis-client-config-cm.yaml
- charts/icm-as/tests/ingress_test.yaml
- charts/icm-as/tests/redis_client_config_test.yaml
- charts/icm-as/tests/weblayer_test.yaml
- charts/icm-as/values.yaml
- charts/icm/requirements.yaml
- charts/icm/values.yaml
- ct_icm.yaml
- redis configuration in webLayer
- ingress session affinity configuration
- redis service and deployment
- tests for webLayer, ingress
Issue Number: Closes #335
> feat(icm): redis configuration (#335)

- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/values.yaml
- charts/icm-web/templates/wa-deployment.yaml
- charts/icm-web/templates/waa-deployment.yaml
- charts/icm-web/values.yaml
Issue Number: Closes #405
Rolling updates are working without reducing the number of pods during update
> feat (icm): support-rolling-updates (#405)

- charts/pwa/templates/prefetch-job.yaml
[x] Bugfix
patch
Issue Number: Closes #399
fixed
[ ] Yes
[x] No
> fix(pwa): less verbose wget

- charts/iom/README.rst
- charts/iom/docs/ParametersIOM.rst
> docs(iom): fixed description and link (#87740, #87733)

- .github/workflows/release-branch.yml
> fix: broken branch ref

- charts/iom/README.rst
- charts/iom/docs/ParametersIOM.rst
- charts/iom/templates/_ish.tpl
- charts/iom/templates/jwt-autosecret.yaml
- charts/iom/templates/statefulset.yaml
- charts/iom/values.yaml
The default value of *oms.jwtSecret* has changed. It's empty now. If *oms.jwtSecretKeyRef* is empty too, a random secret will be automatically created and used in this case.
> feat(iom)!: provide auto generated JWT secret

- .github/workflows/release-charts.yml
No manual release is possible.
Issue Number: Closes #443
A manual release is possible.
> feat (common): allow manual release (#443)

- .github/template/base/action.yml
The chart-testing-action fails for unknown reason.
Issue Number: Closes #451
The chart-testing-action passes.
> fix: update chart-testing-action (#451)

- charts/icm-as/Chart.yaml
- charts/icm-as/templates/_environments.tpl
- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/templates/jobserver-deployment.yaml
- charts/icm-as/values.yaml
- charts/icm-job/Chart.yaml
- charts/icm-job/README.md
- charts/icm-job/templates/icm-job.yaml
- charts/icm-job/values.yaml
* avoid deployment of controller in icm-as
* extract image/repository to values.yaml
* remove namespace icm-system from helm-template
* move environment variable declaration to _environments.tpl
* remove JOB server group from icm-as in case job server is enabled
Issue Number: Closes #448
> fix: can't enable job server without deploying controller (#448)

- charts/icm-job/README.md
- charts/icm-job/templates/icm-job.yaml
- charts/icm-job/values.yaml
Currently a -dev version of the job controller was used/referenced.
JobController 1.0.0 is used now.
Cluster role binding contains now required namespace of subject.
> fix: integrate jobcontroller official release

- .github/release.yml
- .github/workflows/main-develop-sync.yml
- .github/workflows/release-charts.yml
release notes must be created manually via UI click
Issue Number: Closes #394
the chart-releaser-action initiates the release note creation
Sync PullRequests with label "ignore-for-release-notes" are ignored.
> chore: chart releaser will now also generate release notes (#394)

- charts/iom/README.rst
- charts/iom/docs/ParametersIOM.rst
- charts/iom/templates/_ish.tpl
- charts/iom/values.yaml
> docs(iom): documentation review

- charts/icm-as/templates/as-deployment.yaml
- charts/icm-as/templates/jobserver-deployment.yaml
- labels and annotations from ICMJob will be copied to the jobs being created by the operator based on the ICMJob spec
Labels and annotations of job-specs are not present. 
Labels and annotations are present and can be used for monitoring and to select pods.
> fix: Apply labels and annotations at jobserver-deployment.yaml (#87619)

- CONTRIBUTING.md
> docs: enhance contribution guideline (#480)

- charts/iom/docs/Metrics.rst
- charts/iom/docs/ParametersIOM.rst
Be sure that pull requests are build according to the defined release process [here](https://github.com/intershop/helm-charts/wiki/Release-Process). As a main part to mention here is that the semantic version type will be read from the commit messages (`BREAKING_CHANGE` marks a *major* change, `feat(icm):` marks *minor* changes and the rest will be *patch*. So the developer must already know and is responsible.
> docs(iom): how to provide prometheus metrics for New Relic / OpenTelemetry

- charts/icm-job/templates/icm-job.yaml
- charts/icm-job/values.yaml
The job controller copies labels and annotations to the K8s "Job" labels and annotations. But the goal is that the pod of the job will enriched with the information.
The job controller copies labels and annotations to the K8s "Job Template Spec" labels and annotations. So that the started pod of the job will enriched with the information.
> fix:icm labels for jobserver - controller update

- charts/iom/charts/iom-tests/templates/_helpers.tpl
- charts/iom/charts/iom-tests/templates/deployment.yaml
- charts/iom/charts/postgres/templates/_helpers.tpl
- charts/iom/charts/postgres/templates/deployment.yaml
- charts/iom/templates/_helpers.tpl
- charts/iom/templates/connection-monitor.yaml
- charts/iom/templates/patch-downtime.yaml
- charts/iom/templates/patch-mailhog.yaml
- charts/iom/templates/poddisruptionbudget.yaml
- charts/iom/templates/statefulset.yaml
Be sure that pull requests are build according to the defined release process [here](https://github.com/intershop/helm-charts/wiki/Release-Process). As a main part to mention here is that the semantic version type will be read from the commit messages (`BREAKING_CHANGE` marks a *major* change, `feat(icm):` marks *minor* changes and the rest will be *patch*. So the developer must already know and is responsible.
> fix(iom): upgrade fails (#90582)

- charts/iom/README.rst
- charts/iom/docs/ExampleDemo.rst
- charts/iom/docs/ExampleProd.rst
- charts/iom/docs/ParametersIOM.rst
- charts/iom/templates/connection-monitor.yaml
- charts/iom/templates/statefulset.yaml
- charts/iom/values.yaml
Be sure that pull requests are build according to the defined release process [here](https://github.com/intershop/helm-charts/wiki/Release-Process). As a main part to mention here is that the semantic version type will be read from the commit messages (`BREAKING_CHANGE` marks a *major* change, `feat(icm):` marks *minor* changes and the rest will be *patch*. So the developer must already know and is responsible.
> feat(iom)!: remove log metadata (#91368)

- charts/icm-as/tests/jvm-config_test.yaml
- charts/icm-as/values.yaml
Closes [AB#88497](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88497)
> fix(icm-as): K8s Memory Pressure

- charts/pwa/templates/deployment_memcached.yaml
- charts/pwa/values.schema.json
- charts/pwa/values.yaml
Some Memcached settings were hard coded
Some Memcached settings can now be configured via flux
> feat(pwa): make memcached more configurable via flux

- charts/iom/Chart.yaml
- charts/iom/README.rst
- charts/iom/docs/ParametersIOM.rst
- charts/iom/values.yaml
> feat(iom)!: updated versions of iom and dbaccount (#91917)

- charts/iom/README.rst
- charts/iom/charts/postgres/Chart.yaml
- charts/iom/docs/ParametersPostgres.rst
> feat(iom)! changed default image tag for postgres from 12 to 15 (#90894)

- charts/iom/README.rst
- charts/iom/docs/ParametersIOM.rst
- charts/iom/values.yaml
> feat(iom)!: reduce memory usage of java from 85% to 80% (#80803)

- charts/iom/README.rst
- charts/iom/docs/ParametersIOM.rst
- charts/iom/templates/resetDataOutdated.yaml
- charts/iom/templates/statefulset.yaml
- charts/iom/values.yaml
> feat(iom)!: removed dbaccount.resetData (#91918)

- charts/iom/charts/postgres/templates/persistenceDynamic.yaml
- charts/iom/charts/postgres/templates/persistenceLocal.yaml
- charts/iom/charts/postgres/templates/persistenceStatic.yaml
…209)
- [ x ] Bugfix
- [ x ] No
> bug: installation failed with postgres.persistence.enabled:false (#93209)

- charts/iom/.helmignore
- charts/iom/templates/ingress.yaml
> chore(iom): incorporated changes made by Helm 3.14 (#93550)

- charts/iom/README.rst
- charts/iom/docs/ParametersIOM.rst
- charts/iom/templates/statefulset.yaml
- charts/iom/values.yaml
> feat(iom): allow configuration of metrics endpoint (#93564)

- charts/pwa/templates/prefetch-job.yaml
- charts/pwa/values.schema.json
- charts/pwa/values.yaml
The arguments for the prefetch job were hard coded in the helm chart
The arguments for the prefetch job can now be configured via values.yaml
No breaking change, if no args are provided, the default settings will apply (same as before the change)
- [n] No
> feat(pwa): make prefetch job args configurable via flux

- charts/icm-as/templates/_environments.tpl
- charts/icm-as/tests/environment_test.yaml
- charts/icm-as/values.yaml
⚠️ Database password provision in plain text.
🔒 Database password provision via secret key ref.
Closes #143
Closes [AB#87193](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/87193)
> feat(icm): Database password via secretKeyRef (#143)

- charts/icm-as/templates/_environments.tpl
- charts/icm-as/templates/config-newrelic-yaml-cm.yaml
- charts/icm-as/tests/newrelic_test.yaml
- charts/icm-as/values.yaml
⚠️ New Relic license key provision in plain text.
🔒 New Relic license key provision via secret key ref.
Closes #540
Closes [AB#93898](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/93898)
> feat(icm): New Relic license via secretKeyRef (#540)

- charts/icm-as/templates/_environments.tpl
- charts/icm-as/tests/environment_test.yaml
- charts/icm-as/values.yaml
Environment variables via secret key ref not possible.
Environment variables via secret key ref possible.
Closes #550
Closes [AB#94360](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/94360)
> feat(icm): Environments via secretKeyRef (#550)

- .github/labeler.yml
- .github/workflows/pr-labeler.yml
> fix: Usage of actions/labeler@v5

- .github/template/base/action.yml
- .github/workflows/lint-test_pwa.yml
- .github/workflows/release-charts.yml
Known issue: https://github.com/Azure/setup-helm/issues/126
Set specific version 4.0.0 of `azure/setup-helm` action.
> chore: Set explicit version of GitHub azure/setup-helm Workflow Actions (#549)

- charts/icm-replication/start-test-local.sh
- charts/icm/start-test-local.sh
Script fails
Issue Number: Closes #576
Script passes
> fix (icm): use default value initialization (#576)

- charts/icm/templates/test-job.yaml
Sometime tests fail due to a missing ingress controller
Issue Number: Closes #603
Ingress controller is checked before test starts
> fix(icm): ingress controller is checked (#603)

- charts/icm/values-iste_linux.tmpl
test fails with 412 Request Entity Too Large 
Issue Number: Closes #615
test will not fail
> fix(icm): change to correct parameter (#615)

- .gitignore
- charts/icm-replication/start-test-local.sh
- charts/icm/start-test-azure.sh
- charts/icm/start-test-azure_vars.sh
- charts/icm/start-test-local.sh
- charts/icm/values-test-azure.tmpl
Execution of a single testsuite in azure is difficult.
Issue Number: Closes #642
Execution is simplified
> feat: add scripts for azure test execution (#642)

- charts/icm-as/Chart.yaml
- charts/icm-as/release-notes/2.0.0.md
- charts/icm-as/templates/_volumeMounts.tpl
- charts/icm-as/templates/_volumes.tpl
- charts/icm-as/templates/cluster-encryption-pvc.yaml
- charts/icm-as/templates/cluster-encryption-sc.yaml
- charts/icm-as/templates/local-encryption-pv.yaml
- charts/icm-as/templates/local-encryption-pvc.yaml
- charts/icm-as/templates/nfs-encryption-pv.yaml
- charts/icm-as/templates/nfs-encryption-pvc.yaml
- charts/icm-as/templates/static-encryption-pvc.yaml
- charts/icm-as/templates/static-sites-pvc.yaml
- charts/icm-as/tests/persistence-sites_test.yaml
- charts/icm-as/values.yaml
- charts/icm/Chart.yaml
- charts/icm/values.yaml
Issue Number: Closes #653 
additional volume for encryption files
> volume for encryption files

- charts/icm-as/templates/_environments.tpl
Issue Number: Closes #651 
In case job server is enabled the server groups BOS,WFS,EDI are enabled to serve requests.
> fix: server group assignment in case job server is enabled (#651)

- charts/icm-as/templates/cluster-encryption-sc.yaml
Automatic StorageClass usage would fail
Issue Number: Closes #678
Automatic StorageClass usage would succeed
> fix(icm): fix typo (#678)

- charts/icm-replication/values-iste_linux.tmpl
- charts/icm-replication/values-test-local.tmpl
- charts/icm/values-iste_linux.tmpl
- charts/icm/values-test-local.tmpl
Some iste tests fail due to certificate error. Local replication test not possible.
Issue Number: Closes #677
No certificate error anymore. Local replication test possible.
> fix(icm): fix local repl. exec and enable CSI secret creation (#677)

- charts/icm-replication/values-iste_linux.tmpl
- charts/icm-replication/values-test-local.tmpl
- charts/icm/values-iste_linux.tmpl
- charts/icm/values-test-local.tmpl
Test fail with UnknownHostException
Issue Number: Closes #709
Test do not fail with UnknownHostException
> fix: remove csi volume mount (#709)

- charts/icm-replication/values-iste_linux.tmpl
- charts/icm/values-iste_linux.tmpl
End2end test template contains commands to be overwriten in wa and waa. But these endpoints aren't available anymore.
Issue Number: Closes #793
No wa and waa command overwrites
> fix(icm): no command overwrite in wa and waa (#793)

- .github/template/base/action.yml
- .github/template/unittest/action.yml
- Update helm unittest dependency (0.3.3 -> 0.6.1)
- fixes different template error output in old version 0.3.3
- provides support for newer unit test functionality
- both needed/used in PR #803
- Migrate deprecated helm unit test result publishing workflow action "EnricoMi/publish-unit-test-result-action"
> chore(icm): Update helm unittest dependencies

- charts/pwa/.bumpversion.toml
- charts/pwa/Chart.yaml
- charts/pwa/README.md
- charts/pwa/templates/prefetch-job.yaml
- charts/pwa/values-flux.schema.json
* fix for "add options to configure `successfulJobsHistoryLimit` and `failedJobsHistoryLimit` for the prefetch job"
* moved configuration to the right place in the template
> feat(pwa): fix for "add options to configure `successfulJobsHistoryLimit` and `failedJobsHistoryLimit` for the prefetch job"

- charts/icm-as/templates/cluster-encryption-sc.yaml
- charts/icm-as/tests/persistence-encryption_test.yaml
- charts/icm-as/tests/update-strategy_test.yaml
> Add unit tests for encryption volume and update strategy

- charts/icm-as/templates/kpi-exporter-cronjob.yaml
- charts/icm-as/tests/kpi-exporter-cronjob_test.yaml
- charts/icm-as/values.yaml
Business Resource KPI are not exported for further tracking.
Issue Numbers:
- Closes #832 
- Closes [AB#100553](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/100553)
Business Resource KPI are exported as CSV to Azure Functions for further tracking.
> feat(icm): ICM-AS KPI-Exporter Integration (#100553)

- charts/icm-web/values.yaml
The old WAA has some issues regarding error handling and synchronization issues with the used Lucene index.
The resource limits were too low, so that all installations must adapt these values. OOM occurred in case the WAA had something to do.
This update contains the update of the WebAdapterAgent, which is responsible to keep the pagecache up2date.
This …
> fix: update WAA to 5.1.0 and adapt resource defaults

- .github/template/base/action.yml
- charts/icm-as/templates/kpi-exporter-cronjob.yaml
- charts/icm-as/tests/kpi-exporter-cronjob_test.yaml
Currently the KPI exporter cronjob is executed only on the first day of each month.
Issue Number: Closes #102730 
The KPI exporter cronjob is executed every day.
> fix(icm): update kpi exporter schedule date (#102730)

- charts/icm-as/templates/jgroups-config-xml-cm.yaml
- charts/icm-as/tests/jgroups-config_test.yaml
- charts/icm-as/values.yaml
- [ x] Feature
The directory location for jgroups file_ping is hard-coded to /intershop/jgroups-share
Issue Number: Closes #685
The directory location for jgroups file_ping discovery protocol is optionally configurable, now.
- [ x] No
> feat(icm): jgroups location directory configurable (#865)

- CONTRIBUTING.md
- charts/icm-as/values.yaml
- charts/icm/README.md
- charts/icm/values.yaml
There is no link to the Release Process-document within the contribution rules.
Issue Number: Closes #867
Contribution rules and release process are linked. Some commented code indentation was removed.
> docs(common): link "Release Process"-wiki page to the contribution rules (#867)

- charts/icm-as/templates/_environments.tpl
- charts/icm-as/tests/replication_test.yaml
- charts/icm-as/values.yaml
- [x ] Bugfix
Issue Number: Closes #884
> fix(icm): fix error message about mutual exclusive databaseName/database configuration

- charts/iom/Chart.yaml
- charts/iom/README.rst
- charts/iom/templates/patch-downtime.yaml
- charts/iom/values.yaml
kubectl image is hardcoded
Issue Number: Closes #900
kubectl image is configurable
> fix: make kubectl image configurable (#900)

- charts/icm-as/templates/config-newrelic-yaml-cm.yaml
- charts/icm-as/tests/newrelic_test.yaml
- charts/icm-web/templates/config-newrelic-yaml-cm.yaml
- charts/icm-web/tests/nr_test.yaml
New Relic agent forwards decorated logs directly to new relic. Regular logs (Stdout) are not decorated. Therefore we have increased log ingress. Furthermore the log level settings (thresholds) are apparently ignored by the log forwarder.
Issue Number: Closes #914 
The New Relic Java Agent decorates logs with trace / span ids when APM is enabled. The data is forwarded by the …
> fix(icm): disable integrated NR agent log forwarding

- charts/icm/docs/configmapmounts-kustomize.rst
.
The ConfigmapMount documentation has been extended with additional examples and explanations.
> docs(icm): Add explanations and examples to ConfigMapMounts documentation

- charts/icm-as/tests/default-values_test.yaml
- charts/icm-as/values.yaml
> fix(icm): consume infrastructure-probing:3.0.0 (#1018)

- .github/workflows/main-develop-sync.yml
- When trying to use a direct merge into the develop branches we ran into problems because of repository rulesets that don't allow this. 
Issue Number: Closes #1067
- To fix this, we now still use a pull request, however, it is now automergable (with the squash commits merge strategy) to reduce manual labor but still allow it for the repository.
- When there are merge …
> feat: Optimise Helm Chart Release Process

- .github/workflows/main-develop-sync.yml
- Pull request uses squash merge strategy into develop branches but that makes histories of the branches incomparable
Issue Number: Closes #1067
- Pull request now uses merge as merge strategy
> Fix: Use Merge Strategy instead of Squash Strategy

- charts/icm-job-test/values-iste_linux.tmpl
- charts/icm-replication/values-iste_linux.tmpl
- charts/icm/values-iste_linux.tmpl
An external ingress service is created.
Issue Number: Closes #1107 
An external ingress service is **NOT** created.
> fix(icm): disable external ingress service (#1107)
