charts/pwa/docs/migrate-to-0.3.0.md
charts/pwa/templates/ingress.yaml
charts/pwa/values.yaml

[X] Bugfix
[ ] Feature
Depending on the Kubernetes version you are using, the definition of ingress resources has to be changed. If you are using Kubernetes version >= 1.19 ingress resources are now using api-version [networking.k8s.io/v1](http://networking.k8s.io/v1). Older versions of PWA Helm charts always used api-version [networking.k8s.io/v1beta1](http://networking.k8s.io/v1beta1). Therefore warnings like this appeared when installing in Kubernetes:
```
Warning:  templates/ingress.yaml: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in …
```

Fix usage of outdated ingress definition

---

charts/icm-replication/.bumpversion.cfg
charts/icm-replication/Chart.yaml
charts/icm-replication/requirements.yaml
charts/icm-replication/values.yaml
charts/icm-web/.bumpversion.cfg
charts/icm-web/Chart.yaml
charts/icm-web/templates/wa-deployment.yaml
charts/icm-web/values.yaml
charts/icm/.bumpversion.cfg
charts/icm/Chart.yaml
charts/icm/requirements.yaml
charts/icm/values.yaml

[ ] Bugfix
[x] Feature
[x] Application / infrastructure changes
Currently HTTP/1.1 is used by the webserver / webadapter.
Issue Number: Closes #69637 (Azure Issue)
HTTP/2 is enabled by default in webadapter version 2.4.0 and can be disabled if required with the `disableHTTP2` configuration value or environment variable `ICM_WEBSERVER_DISABLE_HTTP2` respectively.
[ ] Yes
[x] No

ICM: Enable HTTP/2 protocol by default

---

charts/icm-web/templates/wa-deployment.yaml

[x] Bugfix
helm install fails when using either cluster or nfs as persistence layer.
Issue Number: Closes #112

ICM: fix nfs persistence definition (#112)

---

charts/icm-as/templates/as-deployment.yaml
charts/icm-as/templates/as-service.yaml
charts/icm-as/templates/cluster-sites-sc.yaml
charts/icm-as/values.yaml
charts/icm-web/values.yaml

[ ] Bugfix
[x] Feature
When using cluster as persistence type for pagecache and sites the folders are owned by root. No `chown` can change this. The solution is and own storage class setting the right owner.
Issue Number: Closes #116

feat: cluster persistence owner shall be 150 (intershop) (#116)

---

.github/pull_request_template.md

[ ] Bugfix
[ ] Feature
[ X ] Documentation content changes
> Can we add a reminder to manually set the major/minor/patch label to the PR template? Like some other "PR checklists" as seen on open source projects

doc: Include a hint to select a label in pr-template

---

charts/pwa/README.md
charts/pwa/templates/_helpers.tpl
charts/pwa/templates/prefetch-job.yaml
charts/pwa/values.schema.json
charts/pwa/values.yaml

[ ] Bugfix
[ x ] Feature
Preheat the nginx or other caches of upstream services is not supported. The PWA deployment does not provide the means to automatically crawl pages in a schedule based manner.
Include this in your `values.yaml`:
```yaml
prefetch:
- host: some.site.com
```
to heat up caches for your deployment behind `https://some.site.com/`
[ ] Yes
[X] No

feat: support page prefetch

---

charts/pwa/README.md
charts/pwa/templates/_helpers.tpl
charts/pwa/templates/prefetch-job.yaml
charts/pwa/values.schema.json
charts/pwa/values.yaml

[ ] Bugfix
[x] Feature
[x] CI-related changes
Preheat the nginx or other caches of upstream services is not supported. The PWA deployment does not provide the means to automatically crawl pages in a schedule based manner.
Include this in your `values.yaml`:
```yaml
prefetch:
- host: some.site.com
```
to heat up caches for your deployment behind `https://some.site.com/`
[ ] Yes
[x] No

release: pwa-main version 0.5.0

---

charts/icm-as/templates/as-deployment.yaml
charts/icm-as/tests/persistence-jgroups_test.yaml
charts/icm-as/values.yaml

[ ] Bugfix
[x] Feature
Issue Number: Closes #191
Azure Files can be used as volume for jgroups.
[ ] Yes
[x] No

add azure file for jgroups (#191)

---

charts/pwa/.bumpversion.cfg
charts/pwa/README.md
charts/pwa/templates/deployment.yaml
charts/pwa/templates/deployment_cache.yaml
charts/pwa/templates/service.yaml
charts/pwa/templates/service_cache.yaml
charts/pwa/values.schema.json
charts/pwa/values.yaml

[ ] Bugfix
[ X ] Feature
PWA has prometheus metrics endpoint for quite some time now. Still the HELM chart did not contain any means to enable metrics nor did it have means to attach annotations necessary for monitoring solutions.
You can use `podAnnotations` to include annotations necessary for your monitoring solution. As well as having two switches with which metrics can be switched off and on. 
All new objects are optional. Prometheus metrics are disabled by default.
[ ] Yes
[ X ] No

feat: support prometheus metrics

---

charts/icm-as/templates/as-deployment.yaml
charts/icm-as/tests/basic-config-values_test.yaml
charts/icm-as/tests/default-values_test.yaml
charts/icm-as/values.yaml

[ ] Bugfix
[x] Feature
The application server pod termination grace period _cannot_ be modified by the `values.yaml`.
No K8s life cycle hooks are executed.
Issue Number: Closes #74660 (ADO)
The application server pod termination grace period _can_ be modified by the `values.yaml`.
A HTTP request it sent to the application server for the K8s preStop life cycle hook.
[ ] Yes
[x] No

feat: Graceful termination of icm-as

---

charts/icm/templates/test-job.yaml
charts/icm/values-iste_linux.tmpl

[x] Bugfix
pagedump zip is not working
Issue Number: Closes #237
zipping works
[ ] Yes
[x] No

fix (icm): zip must be installed exactly before usage (#237)

---

charts/icm-web/templates/wa-deployment.yaml
charts/icm-web/templates/waa-deployment.yaml
charts/icm-web/values.yaml
charts/icm/values-iste_linux.tmpl
charts/icm/values-test-local.yaml

[x] Feature
there is no emptyDir option for pagecache
Issue Number: Closes #176
emptyDir is possible for pagecache
[ ] Yes
[x] No

feat (icm): enable emptyDir for pagecache volume (#176)

---

.gitignore
charts/icm-as/templates/as-deployment.yaml
charts/icm-as/tests/custom-command_test.yaml
charts/icm/README.md
charts/icm/start-test-local.sh
charts/icm/start-test-local_vars.sh
charts/icm/tests/default-values-test_test.yaml
charts/icm/values-iste_linux.tmpl
charts/icm/values-test-local.tmpl

[x] Feature
* There are no logs of icm-as, icm-wa and icm-waa stored to file system (local or nfs) during test execution.
* `./start-test-local.sh` is to complex to start
Issue Number: Closes #249
* Logs are stored in filesystem during testexecution
* `./start-test-local.sh` is simplified
[x] No

feat (icm): enable log output to volume mount (#249)

---

charts/icm/values-iste_linux.tmpl

[x] Feature
http access during test execution is not allowed but needed since redirect is not working
Issue Number: Closes #256
http access is allowed
[x] No

feat (icm): allow http access since redirect is not working (#256)

---

charts/icm/values-iste_linux.tmpl

[x] Bugfix
Still there is a timezone set
Issue Number: Closes #276
There is no timezone set and icm-as uses UTC
[ ] Yes
[x] No

fix (icm): remove last timezone tag (#276)

---

charts/icm-as/templates/as-deployment.yaml
charts/icm-as/templates/ingress.yaml
charts/icm-as/templates/ssl-certificate-spc.yaml
charts/icm-as/values.yaml

[ x ] Bugfix
[ x ] Feature
Currently the WebAdapter (configured in the icm-web chart) is required in all deployments. This PR introduces the changes necessary for deployments without the WebAdapter / WebAdapterAgent (and without the icm-web chart in general)
Issue Number: Closes 85748 
- an ingress can be configured within the icm-as chart (disabled by default) which points directly to the …

feat(icm): enable operation without WA (#85748)

---

charts/icm/values.yaml

[x] Bugfix
Mailhog is enabled by default
Issue Number: Closes #291
Mailhog is disabled by default
[ ] Yes
[x] No

fix (icm): turn off mailhog by default (#291)

---

charts/icm-as/Chart.yaml
charts/icm-as/templates/_initContainer.tpl
charts/icm-as/tests/customizations_test.yaml
charts/icm/Chart.yaml
charts/icm/start-test-local.sh
charts/icm/templates/test-job.yaml
charts/icm/values-iste_linux.tmpl

It's not possible to release because of `runAsNonRoot: true`. The local volume hacks do not work with that. But also seems that we don't need them anymore as there where updates to "DockerDesktop".
Issue Number: Closes #322
Helmchart could be released

feat (icm): remove local volume hacks (#322)

---

charts/icm-web/values.yaml
charts/icm/requirements.yaml
charts/icm/values.yaml

When using the icm umbrella chart, icm-web is always included.
Issue Number: Closes #321 
The icm-web chart can be disabled by setting `icm-web.enabed: false`. The default is `icm-web.enabed: true`.

feat(icm): allow disabling icm-web from icm chart

---

charts/pwa/templates/prefetch-job.yaml

Prefetch job is running on customized alpine image. Customized in a way that it forcefully exits after a given amount of time. That alpine version is **3.16**.
Alpine version is now **3.18**
[Alpine Release Page](https://www.alpinelinux.org/releases/)

Bump to alpine 3.18

---

charts/icm-job/templates/icm-job.yaml

icm-job could not deploy
Issue Number: Closes #340
icm-job deploys

fix (icm): imagePullSecret couldn't be read (#340)

---

charts/icm-replication/values-iste_linux.tmpl
charts/icm-replication/values-test-local.tmpl

edit and live are connected via jgroups
Issue Number: Closes #356
edit and live are not connected via jgroups

fix (icm): remove jgroups connection between edit and live (#356)

---

charts/icm-replication/values-iste_linux.tmpl
charts/icm/Chart.yaml
charts/icm/values-iste_linux.tmpl

WAA memory limit is unneeded high for test execution
Issue Number: Closes #369
WAA has the amount of memory it needes

feat (icm): reduce memory limit for test execution (#369)

---

charts/icm-as/templates/ssl-certificate-spc.yaml
charts/icm-as/values.yaml
charts/icm-web/templates/ssl-certificate-spc.yaml
charts/icm-web/values.yaml

The current helm chart icm-web and icm-as don't support new K8s version. Because
`apiVersion: secrets-store.csi.x-k8s.io/v1alpha1` is used.
This PR allows using `apiVersion: secrets-store.csi.x-k8s.io/v1` as well.
Issue Number: Closes #384 
to enable the _secrets-store.csi.x-k8s.io/v1_ please use:
```
sslCertificateRetrieval:
supportV1: true
```
In the new major version, this default configuration will be changed to "true", so that usage of deprecated v1apha1 will be supported additionally.

feat: support secrets store csi v1  (#384)

---

charts/icm-as/.bumpversion.cfg
charts/icm-job/.bumpversion.cfg
charts/icm-replication/.bumpversion.cfg
charts/icm-web/.bumpversion.cfg
charts/icm/.bumpversion.cfg

Chart.yaml entries are not replaced correctly
Issue Number: Closes #405
Chart.yaml entries are replaced correctly

fix (common): values will be correctly replaced (#405)

---

charts/icm-as/templates/_environments.tpl
charts/icm-as/templates/_helpers.tpl
charts/icm-as/templates/_initContainer.tpl
charts/icm-as/templates/_volumeMounts.tpl
charts/icm-as/templates/_volumes.tpl
charts/icm-as/templates/as-deployment.yaml
charts/icm-as/templates/cluster-jgroups-pvc.yaml
charts/icm-as/templates/jgroups-config-xml-cm.yaml
charts/icm-as/templates/jgroups-kubeping-cr.yaml
charts/icm-as/templates/jgroups-kubeping-crb.yaml
charts/icm-as/templates/jobserver-deployment.yaml
charts/icm-as/templates/local-jgroups-pvc.yaml
charts/icm-as/templates/serviceaccount.yaml
charts/icm-as/tests/jgroups-config_test.yaml
charts/icm-as/tests/jgroups-kubeping-cluster-roles_test.yaml
charts/icm-as/tests/serviceaccount-create_test.yaml
charts/icm-as/values.yaml

This is a `minor` release allowing to configure jgroups-discovery modes.
ICM-AS uses FILE_PING as jgroups discovery mode. To support that, a persistent volume is necessary and configured in the helm chart.
The ServiceAccount can be used in case the chart can create the account, only.
ICM-AS can now use different jgroups discovery modes. The most fitting mode is KUBE_PING. In order to allow to configure this mode a config map jgroups-config.xml is used and cluster roles and bindings are provided.
The service account can be created and used by jgroups, the configuration of the service account allows to define use an existing service account name.
To enable KUBE_PING, the icm-as pods are assigned to a service account. This service account has permissions to read pods inside the namespace.

Support Several JGroups Discovery Modes

---

charts/pwa/README.md
charts/pwa/ci/cache-channels.yaml
charts/pwa/templates/NOTES.txt
charts/pwa/templates/deployment.yaml
charts/pwa/templates/deployment_cache.yaml
charts/pwa/values.schema.json
charts/pwa/values.yaml

- Default rolling update can cause that new nginx instances cache old ssr content.
- ~~Both nginx and ssr have to be in sync all the time, so the strategy `Recreate` is used.~~
- Added initContainer for nginx waiting on pwa availability
- repaired notes
- The update strategy is configurable so now `Recreate` can be used when problems appear. (Default behavior is still `RollingUpdate`)

PWA chart improvements

---

charts/pwa/README.md
charts/pwa/ci/cache-channels.yaml
charts/pwa/docs/migrate-to-0.8.0.md
charts/pwa/templates/NOTES.txt
charts/pwa/templates/ingress.yaml
charts/pwa/values.schema.json
charts/pwa/values.yaml

[x] Application / infrastructure changes
major
- The ingress declaration supposedly enables the PWA to be deploued flexible in a context path, which will not work
- The `ingresssplit` definition with b4cab60 introduces a lot of code duplication.
- new format of declaring ingress
- removed declarable paths
- removed duplication
- removed handling of older kubernetes clusters for the sake of chart readability
[x] Yes
[ ] No

refactor: new ingress format

---

charts/icm-as/values.yaml

Helm chart value configurations follow camel case, however the key "newrelic.license_key" does not.
For consistent naming - also in terms of alignment with the IOM helm charts - we should deprecate (and eventually remove) "license_key".
"license_key" is deprecated.
Fixes [AB#94232](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/94232)

fix(icm): Deprecate icm-as.newrelic.license_key

---

charts/icm-as/templates/config-newrelic-yaml-cm.yaml
charts/icm-as/tests/newrelic_test.yaml
charts/icm-as/values.yaml
charts/icm-replication/values-iste_linux.tmpl
charts/icm/values-iste_linux.tmpl

Helm chart value configurations follow camel case, however the key `icm-as.newrelic.app_name` does not.
For consistent naming - also in terms of alignment with the IOM helm charts - we should deprecate (and eventually remove) `app_name` and replace it with `appName`.
`app_name` is deprecated. Provided `appName` instead.
Fixes [AB#94232](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/94232)

fix(icm): Deprecate icm-as.newrelic.app_name and provide appName instead

---

charts/pwa/docs/migrate-to-0.8.0.md
charts/pwa/values.yaml

[x] Documentation content changes
The `ingress` declaration format changes in PWA Helm Chart 0.8.0 where not clear enough.
Examples and more documentation was added to address occurring problems with migrating to the new PWA Helm Chart 0.8.0.
[x] No

docs: improve PWA Helm Chart 0.8.0 migration documentation

---

charts/icm-web/templates/wa-deployment.yaml
charts/icm-web/values.yaml

ICM WebAdapter lacks startup/liveness/readiness probes for K8s.
In case of non-liveness or non-readiness of the WebAdapter that can lead to eventually broken deployment states.
Closes [AB#95870](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95870)
Closes [AB#95776](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95776)
ICM WebAdapter has configurable startup/liveness/readiness probes for K8s.

feat(icm-web): ICM WebAdapter Probes

---

charts/icm-replication/values.yaml
charts/icm-web/values.yaml
charts/icm/values.yaml

Both WebAdapter and WebAdapterAgent container are not shutting down gracefully and stay running until the [K8s graceful pod shutdown period](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) is exceeded.
Both WebAdapter and WebAdapterAgent container are shutting down gracefully now. This also speed-up the deployment deletion process and saves Node resources, as both container are properly removed almost immediately in comparison to before.
The WebAdapter `2.5.0` and WebAdapterAgent `4.0.1` Docker Images contains fixes for the shutdown process on container level. Plus the fixes on icm-web helm chart level for both container commands.
Issue Number:
Fixes [AB#97203](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/97203) …

fix(icm-web): Graceful Container Shutdown of WebAdapter and WebAdapterAgent (#97203)

---

charts/icm/templates/test-job.yaml

Currently the testrunn start when readyness probe of icm-as is successful
Issue Number: Closes #286
icm-web-wa/INTERSHOP/wastatus is checked correctly

fix(icm): check wa instead of as (#286)

---

charts/icm-web/templates/wa-deployment.yaml
charts/icm-web/values.yaml

According to the default topology constraints a max. skew of 3 node hostnames regarding scheduled WA pods is possible.
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#internal-default-constraints
Configuration introduced to try to evenly schedule WA pods across different nodes.
Issue Number:
Fixes [AB#97982](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/97982)

feat(icm-web): Try to schedule WA pods evenly over different nodes

---

charts/icm-replication/values-iste_linux.tmpl
charts/icm/values-iste_linux.tmpl

Currently we use NFS to store test related data. With the switch to Azure Fileshare with SMB the modified date of files is not updated when changing it. But for a testrun the modified date is needed as the iste-execution-service checks it for recent changes. If the modified date is older than e.g. an hour the test aborts. This would abort well running tests.
Issue Number: Closes #716
As long as the test runs the modified date of the `istestrunner_log.txt` is update via a workaround by checking the file size.

feat(icm): use logger instead of tee (#716)

---

charts/icm-as/templates/cluster-jgroups-pvc.yaml
charts/icm-as/templates/cluster-jgroups-sc.yaml
charts/icm-as/tests/persistence-jgroups_test.yaml

own configured jgroups StorageClass is missing. Instead the sites-sc is used.
Issue Number: Closes #751
own jgroups persistence storageClass enabled

fix(icm): the jgroups now has its own sc (#751)

---

charts/icm-web/templates/ingress.yaml
charts/icm-web/values.yaml

Access to internal WA endpoints permitted per default and no configuration available to allow IPs to access those endpoints.
Issue Number:
Fixes [AB#98249](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/98249)
Access to internal WA endpoints denied per default and configuration available to allow IPs to access those endpoints.

feat(icm): Configurable access to internal WA endpoints

---

charts/icm-as/templates/as-deployment.yaml
charts/icm-web/templates/wa-deployment.yaml
charts/icm-web/templates/waa-deployment.yaml

ADO working item (#97788)
It' a minor change, because without the environment can't shutdown the servers. (and keep the infrastructure)
Defining replicaCount=0 doesn't lead to a total shutdown, because the default value=1 overrules that definition.
Issue Number: Closes #787
default value in templates is set to 0 (doesn't overrule) values.yaml still defines 1 as default. …

feat(icm): allow shutdown via replicas=0 definition (#787)

---

charts/icm-as/templates/_operationalContext.tpl
charts/icm-as/tests/operational_context_test.yaml

Invalid generated operational-context labels for icm-as in replication context.
Issue Number: Closes #800 / [AB#99384](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/99384)
Valid generated operational-context labels for icm-as in replication context plus added test coverage.

fix(icm): Fix invalid operational context labels in replication context (#800)

---

.gitignore
charts/icm-as/templates/_environments.tpl
charts/icm-as/templates/_helpers.tpl
charts/icm-as/templates/_volumeMounts.tpl
charts/icm-as/templates/_volumes.tpl
charts/icm-as/templates/config-replication-clusters-xml-cm.yaml
charts/icm-as/tests/replication_test.yaml
charts/icm-as/values.yaml
charts/icm-replication/values-iste_linux.tmpl
charts/icm-replication/values.yaml
charts/icm/values.yaml

Helm Charts `icm-replication` (respectively also its "super charts" `icm-as` / `icm`) make use of the replication environment configuration via `replication-cluster.xml`.
Issue Number: Closes #802 / [AB#99130](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/99130)
Helm Charts `icm-replication` (respectively also its "super charts" `icm-as` / `icm`) make use of the replication environment configuration via succeeding configurations in the `icm/values.yaml` / `icm-as/values.yaml` / `icm-replication/values.yaml`.
The former XML based `replication-cluster.xml` can still be used by applying the deprecated values `replication.targetSystemUrl` / `replication.sourceDatabaseName`, but it is not recommended. Instead, make use of the new values …

feat(icm): New replication environment configuration

---

.github/workflows/lint-test_icm-as-integrationtest.yml
charts/icm-as/templates/_environments.tpl
charts/icm-as/templates/_infrastructureMonitoring.tpl
charts/icm-as/templates/as-deployment.yaml
charts/icm-as/templates/infrastructure-monitoring-service.yaml
charts/icm-as/tests/default-values_test.yaml
charts/icm-as/tests/infrastructure-monitoring_test.yaml
charts/icm-as/values.yaml

icm-as-container runs standalone (besides the init-containers) in its pod.
Issue Number: Closes #815
A second container providing a database latency metric runs alongside the icm-as-container.

815 - support infrastructure probing container

---

charts/icm-as/templates/_infrastructureMonitoring.tpl
charts/icm-as/tests/default-values_test.yaml
charts/icm-as/tests/infrastructure-monitoring_test.yaml
charts/icm-as/values.yaml

Disabled infrastructure monitoring probes make the infrastructure monitoring sidecar container fail on startup
Issue Number: Closes #837
Disabled infrastructure monitoring probes no longer make the infrastructure monitoring sidecar container fail on startup

fix: fix inframon jvm-options (#837)

---

charts/icm-web/templates/wa-deployment.yaml
charts/icm-web/values.yaml

timeoutSeconds is not configurable for the webadapter probes
Issue Number: Closes #845
timeoutSeconds is configurable for the webadapter probes

feat (icm): enable timeoutSeconds for icm-wa (#845)

---

charts/icm-web/templates/wa-deployment.yaml

Sometime deployment fails due to a small timeout value for wastatus readiness probe
Issue Number: Closes #852
The default timeout is now set to 5s

fix (icm): wastatus could last longer (#852)

---

charts/icm-as/README.md
charts/icm-as/templates/_helpers.tpl
charts/icm-as/templates/as-deployment.yaml
charts/icm-as/templates/jobserver-deployment.yaml
charts/icm-as/tests/dns_config_test.yaml
charts/icm-as/tests/host_aliases_test.yaml
charts/icm-as/values.yaml

hostAliases and dnsConfig are not configurable in icm-as
Issue Number: Closes #912
hostAliases and dnsConfig are not configurable in icm-as

feat(icm): added hostAliases + dnsConfig config to icm-as (#912)

---

charts/icm-as/templates/_environments.tpl
charts/icm-as/tests/replication_test.yaml
charts/icm-replication/values-test-local.tmpl
charts/icm/values-test-local.tmpl

icm-replication deployment fails when version 12.4.2-SNAPSHOT is used.
Issue Number: Closes #974
icm-replication deployment works also with 12.4.2-SNAPSHOT.

fix: version comparision for replication fixed (#974)

---

charts/icm/docs/configmapmounts-kustomize.rst

There is no documentation or example on how to use configMapMounts in the icm-web Helm chart.
Issue Number: Closes #976
There is documentation with an example on how to use configMapMounts in the icm-web Helm chart.

docs(icm): Add icm configMapMounts docu (#976)

---

charts/icm-as/docs/how-to.asciidoc
charts/icm-as/templates/_environments.tpl
charts/icm-as/templates/_volumeMounts.tpl
charts/icm-as/tests/secret-mounts_test.yaml

Issue Number: Closes #1027
More than 1 certificate / secret can be mounted
Documentation improved

#1027: allow to mount more than 1 certificate

---

charts/icm-as/values.yaml

Issue Number: Closes #1027 
more than 1 certificate can be mounted

fix(icm): allow to mount more than 1 certificate (#1027)

---

charts/icm-job-test/values-iste_linux.tmpl

JobServer tests fail maybe due to missing jgroups configuration
Issue Number: Closes #1059
jgroups is configured

fix(icm): jobserver needs jgroups (#1059)
